config/routes.rb
Rails.application.routes.draw do
    root 'chatroom#index'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    post 'message', to: 'messages#create'
    
    get 'signup', to: 'users#new'
    
    mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    has_many :messages
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true,
        uniqueness: { case_sensitive: false },
        length: { minimum: 3, maximum: 25 }
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    # Prevent CSRF attacks by raising an exception.
    # for APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
       !!current_user 
    end
    
    def require_user
        if !logged_in?
            flash[:negative] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user
    
    def index
        @messages = Message.custom_display
        @message = Message.new
    end
    
    def new
    end

    def edit 
    end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user
    
    def create
        message = current_user.messages.build(message_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel", mod_msg: message_render(message)
        end
    end
    
    private
    
    def message_params
        params.require(:message).permit(:body)
    end
    
    def message_render(message)
        render(partial: 'message', locals: {message: message}) 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in_redirect, only: [:new, :create]
    
    def new
    
    end
    
    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:positive] = "Welcome back to MessageMe, " + user.username
            redirect_to root_path(user)
        else
            flash.now[:negative] = "There was something wrong with your login information"
            render 'new'
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:positive] = "You have successfully logged out of MessageMe"
        redirect_to login_path
    end
    
    private
    def logged_in_redirect
        if logged_in?
            flash[:negative] = "You are already logged in"
            redirect_to root_path
        end
    end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:positive] = "Welcome to MessageMe #{@user.username}"
            redirect_to root_path
        else
           render 'new' 
        end
    end
    
    def edit
    end
    
    def update
        if @user.update(user_params)
            flash[:positive] = "Your account was updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @user.destroy
        flash[:negative] = "User has been deleted"
        redirect_to users_path
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
    
    def set_user
       @user = User.find(params[:id]) 
    end
    
    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:negative] = "You can only edit your own account"
            redirect_to root_path
        end
    end
    
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:negative] = "Only admin users can perform that action"
            redirect_to root_path
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say Something
</h4>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
                <div class="ui feed" id="message-container">
                    <%= render @messages %>      
                </div>
            </div>
            <% if logged_in? %>
                <div class="extra content">
                    <%= form_for(@message, html: {class: 'ui reply form', role: 'form'}, url: message_path, remote: true) do |f| %>
                        <div class="field">
                            <div class="ui fluid icon input">
                                <%= f.text_field :body, placeholder: "Enter a message...", autofocus: true %>
                                <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
                            </div>
                        </div>
                    <% end %>      
                </div>
            <% end %>
        </div>
    </div>    
    
    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui inverted vertical menu">
                  <a class="active item">
                    Home
                  </a>
                  <a class="item">
                    Messages
                  </a>
                  <a class="item">
                    Friends
                  </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class='ui <%="#{name}"%> message'>
        <i class="close icon"></i>
        <div class="header">
            <%= content_tag :div, msg, :id => 'flash_#{name}' if msg.is_a?(String) %>
        </div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", root_path, class: "item" %>
<a class="item">
    Messages
</a>
<div class="right menu">
    <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
            <% if logged_in? %>
                <a class="item"><%= link_to 'Log out', logout_path, method: :delete %></a>
            <% else %>
                <a class="item"><%= link_to 'Log in', login_path %></a>
            <% end %>
            <a class="item"><%= link_to 'Sign up', signup_path %></a>
        </div>
    </div>
    <div class="item">
        <% if !logged_in? %>
            <%= link_to "Login", login_path, class: "ui primary button" %>
        <% else %>
            <%= link_to "Logout", logout_path, method: :delete, class: "ui primary button" %>
        <% end %>
    </div>
</div>

app/views/layouts/_status_messages.html.erb
<% flash.each do |name, msg| %>
    <div class='ui <%="#{name}"%> message'>
        <i class="close icon"></i>
        <div class="header">
            <%= content_tag :div, msg, :id => 'flash_#{name}' if msg.is_a?(String) %>
        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
        <div class="ui container">
            <%= render 'layouts/navigation' %>
        </div>
    </div>
    <div class="ui container">
        <%= render 'layouts/status_messages' %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %>: </em> <%= message.body %> 
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h2 align="center">Sign up for MessageMe - a complete Chat App</h2>

<div class="ui placeholder segment">
    <div class="column">
      <%= form_for(@user, :html => {class: 'ui form', role: 'form'}) do |f| %>
        <div class="field">
          <label>New Username</label>
          <div class="ui left icon input">
            <%= f.text_field :username, class: 'form-control', placeholder: "Username", autofocus: true %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <label>Password</label>
          <div class="ui left icon input">
            <%= f.password_field :password, class: 'form-control', autocomplete: "off" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.submit "Sign up", class: "ui blue submit button" %>
      <% end %>    
    </div>
</div>